FROM node:20-alpine

WORKDIR /app

COPY ["Box Park III/src/package.json", "./"]
RUN npm install --omit=dev

COPY ["Box Park III/src/", "./"]

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "server.js"]
